export const commonInput = [
  {
    label: 'Patient First Name',
    componentType: 'input',
    inputType: 'input',
    placeholder: 'First Name',
    name: 'patientFirstName',
  },
  {
    label: 'Patient Last Name',
    componentType: 'input',
    inputType: 'input',
    placeholder: 'Last Name',
    name: 'patientLastName',
  },
  {
    label: 'Age',
    componentType: 'slider',
    defaultValue: 15,
    type: 'number',
    name: 'age',
    min: 0,
    max: 100,
  },
  {
    label: 'Chest Pain',
    componentType: 'slider',
    defaultValue: 1,
    type: 'number',
    name: 'chestPain',
    min: 0,
    max: 3,
  },
  {
    label: 'Cholesterol',
    componentType: 'slider',
    defaultValue: 120,
    type: 'number',
    name: 'cholesterol',
    min: 20,
    max: 300,
  },
  {
    label: 'Max Heart Rate / Thalach',
    componentType: 'slider',
    defaultValue: 80,
    type: 'number',
    name: 'maxHeart',
    min: 0,
    max: 350,
  },
  {
    label: 'Old Peak',
    componentType: 'slider',
    defaultValue: 0,
    type: 'number',
    name: 'oldPeak',
    min: 0,
    max: 3,
  },
  {
    label: 'Major Blood Vessels',
    componentType: 'slider',
    defaultValue: 1,
    type: 'number',
    name: 'ca',
    min: 0,
    max: 3,
  },
  {
    label: 'Thalassemia',
    componentType: 'slider',
    defaultValue: 2,
    type: 'number',
    name: 'thalassemia',
    min: 1,
    max: 3,
  },
  {
    label: 'Rest BPM',
    componentType: 'range slider input',
    type: 'number',
    name: 'restBPM',
    min: 40,
    max: 200,
  },
]

export const inputFormData = {
  patientFirstName: 'First Name',
  patientLastName: 'Last Name',
  age: 15,
  chestPain: 1,
  restBPM: [40, 200],
  cholesterol: 120,
  maxHeart: 80,
  oldPeak: 0,
  ca: 1,
  thalassemia: 2,
}

export const formDisplayName = {
  patientFirstName: 'Patient First Name',
  patientLastName: 'Patient Last Name',
  age: 'Age',
  chestPain: 'Chest Pain',
  restBPM: 'Resting BPM ',
  cholesterol: 'Cholesterol',
  maxHeart: 'Max Heart Rate',
  oldPeak: 'Old Peak',
  ca: 'CA',
  thalassemia: 'Thalassemia',
  prediction: 'Prediction',
}
